# Generated by Django 4.1.2 on 2022-10-28 23:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('male', 'мужчина'), ('female', 'женщина')], db_column='gender', max_length=10, null=True, verbose_name='пол')),
                ('date_birth', models.DateTimeField(blank=True, db_column='date_birth', null=True, verbose_name='День рождения')),
                ('phone_number', models.CharField(db_column='phone_number', max_length=18, null=True, unique=True, verbose_name='номер телефона')),
                ('name', models.CharField(db_column='name', max_length=20, null=True, verbose_name='имя')),
                ('avatar', models.ImageField(db_column='avatar', null=True, upload_to='', verbose_name='Аватарка пользователя')),
                ('surname', models.CharField(db_column='surname', max_length=20, null=True, verbose_name='фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60, unique=True, verbose_name='название кафедры')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60, unique=True, verbose_name='название дисциплины')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_headman', models.BooleanField(default=False, null=True, verbose_name='Признак старосты')),
                ('grant', models.CharField(db_column='grants', default=False, max_length=60, verbose_name='степендия')),
                ('exam_points', models.SmallIntegerField(db_column='exam_points', verbose_name='баллы за экзамен')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60, verbose_name='название группы')),
                ('course', models.SmallIntegerField(db_column='course', verbose_name='курс')),
                ('type_education', models.TextField(choices=[('magistracy', 'магистратура'), ('undergradute', 'бакалавриат'), ('specialis', 'специалитет')], db_column='type_eduction', max_length=60, verbose_name='тип образования')),
                ('direction', models.CharField(db_column='direction', max_length=60, verbose_name='направление')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('department', models.CharField(db_column='department', max_length=20, verbose_name='кафедра')),
                ('is_lead_department', models.BooleanField(default=False, null=True, verbose_name='Признак председателя кафедры')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_group', to='custom_auth.studygroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to='custom_auth.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60, verbose_name='название учебного заведения')),
                ('city', models.CharField(db_column='city', max_length=50, verbose_name='город')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_teacher', to='custom_auth.department')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_department', to='custom_auth.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='studygroup',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_university', to='custom_auth.university'),
        ),
        migrations.CreateModel(
            name='StudentsGroups',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='custom_auth.studygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_student', to='custom_auth.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_unit_roles', to='custom_auth.studygroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user', to='custom_auth.customuser'),
        ),
        migrations.CreateModel(
            name='DisciplinesTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_disciplines', to='custom_auth.discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines_teachers', to='custom_auth.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_university', to='custom_auth.university'),
        ),
        migrations.AddField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_university', to='custom_auth.university'),
        ),
    ]
