# Generated by Django 4.1.2 on 2022-10-28 23:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60, verbose_name='Название дидактического материала')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Название Дидактического материала')),
                ('type', models.CharField(db_column='type', max_length=60, verbose_name='Тип материала')),
                ('disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.discipline', verbose_name='Дисциплина, к которой принадлежит дидактический материал')),
                ('stGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_StudyGroup', to='custom_auth.studygroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_teacher', to='custom_auth.teacher')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_university', to='custom_auth.university')),
            ],
        ),
    ]
